core/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

from dashboard.views import Dashboard


urlpatterns = [
    url(r'^$', Dashboard.as_view(), name="dashboard"),
    url(r'^index/$', Dashboard.as_view(), name="index"),
    url(r'^accounts/', include('authentication.urls', namespace='user')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^series/', include('series.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^webhooks/', include('webhooks.urls')),
    url(r'^discount/', include('discount.urls')),
]

series/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.SeriesListView.as_view(), name='series-list'),
    url(r'^create/$', views.SeriesCreateView.as_view(), name='series-create'),
    url(r'^(?P<pk>[0-9]+)/', include([
        url(r'^$', views.SeriesDetailView.as_view(), name='series-detail'),
        url(r'^update/$', views.SeriesUpdateView.as_view(), name='series-update'),
        # url(r'^(?P<pk>[0-9]+)/update$', views.ProductUpdate.as_view(), name='product-update'),
        # url(r'^delete/$', views.ScheduleDeleteView.as_view(), name='schedule-delete'),
    ])),
]

series/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

# Create your models here.
class Series(models.Model):
    title = models.CharField(max_length=250)
    vendor_title = models.CharField(max_length=250, blank=True)
    description = models.TextField(blank=True)
    sku = models.CharField(max_length=50)
    vendor = models.ForeignKey('vendors.Vendor')
    shopify_id = models.BigIntegerField(blank=True, null=True)
    published_scope = models.CharField(max_length=250, default="global")

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('series-detail', kwargs={'pk': self.pk})

series/forms.py
from django import forms
from django.utils.text import slugify

from .models import *
from products.models import ProductType


class SeriesCreateForm(forms.ModelForm):
    product_types = forms.ModelMultipleChoiceField(
        queryset=ProductType.objects.all(),
        widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Series
        fields = ['title', 'vendor_title', 'description', 'sku', 'vendor',
                  'product_types']

    def save(self, commit=True):
        instance = super(SeriesCreateForm, self).save(commit=False)
        if commit:
            instance.save()
        # Create Products from Product Types
            for product_type in self.cleaned_data['product_types']:
                title = "%s %s" % (self.cleaned_data['title'], product_type.title)
                product = product_type.products.create(
                    title=title.title(), handle=slugify(title),
                    body_html=self.cleaned_data['description'],
                    vendor=self.cleaned_data['vendor'], series=instance)
                variant = product.variants.create(
                    sku="%s-%s" % (self.cleaned_data['sku'], product_type.code)
                )
        return instance

series/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DeleteView, DetailView)
from django.core.urlresolvers import reverse_lazy, reverse

from .models import *
from .forms import SeriesCreateForm


class SeriesMixin(LoginRequiredMixin):
    model = Series



class SeriesListView(SeriesMixin, ListView):
    pass


class SeriesCreateView(SeriesMixin, CreateView):
    form_class = SeriesCreateForm


class SeriesUpdateView(SeriesMixin, UpdateView):
    fields = ['title', 'vendor_title', 'description', 'sku', 'vendor']


class SeriesDetailView(SeriesMixin, DetailView):
    pass

series/templates/series/series_confirm_delete.html
{% extends 'series/series_list.html' %}
{% load bootstrap3 %}

{% block title %}Delete {{ object }}?{% endblock %}

{% block actions %}{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<form method="post">
			{% csrf_token %}
      <p>Are you sure you want to delete this series?</p>
			<button class="btn btn-danger">Delete</button>
			<a class="btn btn-default" href="{% url 'series-list' %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

series/templates/series/series_detail.html
{% extends 'series/series_list.html' %}
{% load bootstrap3 %}

{% block title %}{{ object }}{% endblock %}

{% block actions %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'series-update' object.pk %}">{{ object }}</a></li>
{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-2">
        <label>SKU</label>
				<p class="form-control-static">{{ object.sku }}</p>
      </div>
			<div class="col-md-4">
				<label>Name</label>
				<p class="form-control-static">{{ object.title }}</p>
      </div>
      <div class="col-md-4">
				<label>Vendor Name</label>
				<p class="form-control-static">{{ object.vendor_title }}</p>
      </div>
			<div class="col-md-2">
				<label>Vendor</label>
				<p class="form-control-static">{{ object.vendor }}</p>
      </div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<label>Description</label>
				<p class="form-control-static">{{ object.description }}</p>
			</div>
		</div>
  </div>
</div>

<div class="hpanel">
	<div class="panel-body">
		<h3>Products</h3>
		<table class="table">
			<thead>
				<th>Name</th>
				<th>Type</th>
			</thead>
			<tbody>
				{% for product in object.products.all %}
				<tr>
					<td><a href="{% url 'product-detail' product.pk %}">{{ product.title }}</a></td>
					<td>{{ product.product_type }}</td>
					<td></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

series/templates/series/series_form.html
{% extends 'series/series_list.html' %}
{% load bootstrap3 %}

{% block title %}{{ object|default:"Create Series" }}{% endblock %}

{% block actions %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
{% if object %}
	<li><a href="{% url 'series-update' object.pk %}">{{ object }}</a></li>
{% else %}
	<li><a href="{% url 'series-create' %}">Create</a></li>
{% endif %}
{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<form method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-2">
          {% bootstrap_field form.sku %}
        </div>
				<div class="col-md-4">
          {% bootstrap_field form.title %}
        </div>
        <div class="col-md-4">
          {% bootstrap_field form.vendor_title %}
        </div>
				<div class="col-md-2">
          {% bootstrap_field form.vendor %}
        </div>
			</div>
			{% bootstrap_field form.description %}

			{% bootstrap_field form.product_types %}

			<button class="btn btn-success">Save Changes</button>
    </form>
  </div>
</div>
{% endblock %}

series/templates/series/series_list.html
{% extends 'base.html' %}

{% block title %}Series{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'series-list' %}">Series</a></li>
{% endblock %}

{% block actions %}
<a class="btn btn-primary" href="{% url 'series-create' %}">Add Series</a>
{% endblock %}

{% block content %}
<div class="hpanel">
  <div class="panel-body">
    <input type="text" class="form-control input-sm m-b-md" id="filter" placeholder="Search in table">
    <table class="table footable table-striped" data-filter="#filter">
      <thead>
        <tr>
          <th>SKU</th>
          <th>Name</th>
          <th>Vendor Name</th>
          <th>Vendor</th>
        </tr>
      </thead>
      <tbody>
      {% for object in object_list %}
      <tr>
        <td>{{ object.sku }}</td>
        <td><a href="{% url 'series-detail' object.pk %}">{{ object.title }}</a></td>
        <td>{{ object.vendor_title }}</td>
        <td>{{ object.vendor }}</td>
      </tr>
      {% empty %}
      <tr><td colspan="4" class="text-center">There are no series.</td></tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}