authentication/urls.py
from django.conf.urls import url

from .models import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^request_reset_password/$', views.request_reset_password, name='request_reset_password'),
    url(r'^reset_password/%s/$' % (TOKEN_PATTERN,), views.reset_password, name='reset_password'),
]

core/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

from dashboard.views import Dashboard


urlpatterns = [
    url(r'^$', Dashboard.as_view(), name="dashboard"),
    url(r'^index/$', Dashboard.as_view(), name="index"),
    url(r'^accounts/', include('authentication.urls', namespace='user')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^series/', include('series.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^webhooks/', include('webhooks.urls')),
    url(r'^discount/', include('discount.urls')),
]

core/forms.py
from django import forms


class SearchForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.queryset = kwargs.pop('queryset')
        super(SearchForm, self).__init__(*args, **kwargs)


class FileForm(forms.Form):
    file = forms.FileField()

core/views.py
from django.views.generic import ListView


class SearchView(ListView):

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['form'] = self.search_form(self.request.GET or None, queryset=self.get_queryset())
        return context

    def get_queryset(self):
        queryset = super(SearchView, self).get_queryset()
        form = self.search_form(self.request.GET or None, queryset=queryset)
        if form.is_valid():
            queryset = form.search()
        return queryset

core/templates/base.html
{% load static from staticfiles %}
{% load i18n %}
{% load kwacros %}

{% kwacro title %}
    {% block title %}Dashboard{% endblock %}
{% endkwacro %}

<!DOCTYPE html>
<html class="no-js">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Page title -->
  <title>{% usekwacro title %}</title>

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <!--<link rel="shortcut icon" type="image/ico" href="favicon.ico" />-->

  <!-- Vendor styles -->
  <link rel="stylesheet" href="{% static 'vendor/fontawesome/css/font-awesome.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/metisMenu/dist/metisMenu.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/animate.css/animate.min.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/select2-3.5.2/select2.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/select2-bootstrap/select2-bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/toastr/build/toastr.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/sweetalert/lib/sweet-alert.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css' %}" />
  <link rel="stylesheet" href="{% static 'vendor/fooTable/css/footable.core.min.css' %}" />
  <!-- <link rel="stylesheet" href="{% static 'vendor/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css' %}" /> -->
  <link rel="stylesheet" href="{% static 'vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />

  <!-- App styles -->
  <link rel="stylesheet" href="{% static 'fonts/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" />
  <link rel="stylesheet" href="{% static 'fonts/pe-icon-7-stroke/css/helper.css' %}" />
  <link rel="stylesheet" href="{% static 'styles/static_custom.css' %}">
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  {% block custom_css %}
  {% endblock %}

</head>

<body>

  <!-- Header -->
  <div id="header">
    <div class="color-line">
  </div>
  <div id="logo" class="light-version">
      <span>
          Jennifer
      </span>
  </div>
  <nav role="navigation">
      <div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
      <div class="small-logo">
          <span class="text-primary">Jennifer Convertibles</span>
      </div>
      <form role="search" class="navbar-form-custom" method="post" action="#">
          <div class="form-group">
              <input type="text" placeholder="Search something special" class="form-control" name="search">
          </div>
      </form>
      <div class="mobile-menu">
        <button type="button" class="navbar-toggle mobile-menu-toggle" data-toggle="collapse" data-target="#mobile-collapse">
          <i class="fa fa-chevron-down"></i>
        </button>
        <div class="collapse mobile-navbar" id="mobile-collapse">
          <ul class="nav navbar-nav">
            <li>
              <a class="" href="">Changelog</a>
            </li>
            <li>
              <a class="" href="{% url 'user:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="navbar-right">
        {% include 'components/toolbar.html' %}
      </div>
  </nav>
  </div>

  <!-- Navigation -->
  <aside id="menu">
    {% include 'components/navigation.html' %}
  </aside>

  <!-- Main Wrapper -->
  <div id="wrapper">
    {% block header %}
    <div class="normalheader normalheader small-header">
      <div class="hpanel">
        <div class="panel-body">
          <div class="row">
            <div class="col-sm-9">
              <h2 class="font-light m-b-xs">{% usekwacro title %}</h2>
            </div>
            <div class="col-sm-3 text-right">
              {% block actions %}{% endblock %}
            </div>
          </div>
          <div id="hbreadcrumb">
            <ol class="hbreadcrumb breadcrumb">
              <li><a href="{% url 'dashboard' %}"><i class="fa fa-home"></i></a></li>
              {% block breadcrumbs %}
              {% endblock %}
            </ol>
          </div>

          <small>{% block subtitle %}{% endblock %}</small>
        </div>
        {% block header_extra %}{% endblock %}
      </div>
    </div>
    {% endblock %}
    <!-- main page elements -->
    <div class="content">
      {% block content %}
      {% endblock %}
    </div>

    <!-- Right Sidebar -->
    <div id="right-sidear">
        <!-- right sidebar elements -->
    </div>

    <!-- Main Wrapper -->
    <footer class="footer">
      <span class="pull-right">
        v{{ version }} (Under Development)
      </span>
      Jennifer Convertibles
    </footer>

  </div>
  <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
  {% comment %}
  <script src="{% static 'vendor/underscore/underscore-min.js' %}"></script>
  {% endcomment %}
  <script src="{% static 'vendor/jquery-ui/jquery-ui.min.js' %}"></script>
  <script src="{% static 'vendor/slimScroll/jquery.slimscroll.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/metisMenu/dist/metisMenu.min.js' %}"></script>
  <script src="{% static 'vendor/iCheck/icheck.min.js' %}"></script>
  <script src="{% static 'vendor/peity/jquery.peity.min.js' %}"></script>
  <script src="{% static 'vendor/sparkline/index.js' %}"></script>
  <script src="{% static 'vendor/nestable/jquery.nestable.js' %}"></script>
  <script src="{% static 'vendor/select2-3.5.2/select2.min.js' %}"></script>
  <script src="{% static 'vendor/toastr/build/toastr.min.js' %}"></script>
  <script src="{% static 'vendor/sweetalert/lib/sweet-alert.min.js' %}"></script>
  <script src="{% static 'vendor/moment/min/moment.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'vendor/fooTable/dist/footable.all.min.js' %}"></script>
  <script src="{% static 'vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>


  <!-- App scripts -->
  <script src="{% static 'scripts/homer.js' %}"></script>

  <script>
    $(function(){
      $('select').select2();
      toastr.options = {
        "debug": false,
        "newestOnTop": false,
        "positionClass": "toast-top-center",
        "closeButton": true,
        "debug": false,
        "toastClass": "animated fadeInDown",
      };

      $('[data-toggle="tooltip"]').tooltip();
      $('.date').datepicker();
      // $('.datetime').datetimepicker();

      $('.footable').footable();
    })
  </script>

  {% for message in messages %}

  <script type="text/javascript">
    $(function(){
      toastr["{{ message.tags }}"]("{{ message }}");
    })
  </script>
  {% endfor %}
  <!--  Feedback form submission -->
  <script>
  $(function(){

    $('form#feedback').submit(function(ev){
      ev.preventDefault();
      var form = $(this);
      $.ajax({
        //url: '',
        data: form.serialize(),
        method: 'POST',
        beforeSend: function(xhr, data) {
          xhr.setRequestHeader("X-CSRFToken", Cookies.get('csrftoken'));
        }
      }).done(function(data){
        $(':input', form).val('');
        sweetAlert("Sent!", "Thanks for the feedback!", "success");
      })
    })
  })
  </script>

  {% block custom_js %}{% endblock %}

</body>

</html>

core/templates/email_base.html
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>HOMER -  Email Template</title>
  <style>
  * {
    font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
    font-size: 100%;
    line-height: 1.6em;
    margin: 0;
    padding: 0;
  }

  img {
    max-width: 600px;
    width: 100%;
  }

  body {
    -webkit-font-smoothing: antialiased;
    height: 100%;
    -webkit-text-size-adjust: none;
    width: 100% !important;
  }

  a {
    color: #348eda;
  }

  .btn-primary {
    Margin-bottom: 10px;
    width: auto !important;
  }

  .btn-primary td {
    background-color: #62cb31;
    border-radius: 3px;
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    font-size: 14px;
    text-align: center;
    vertical-align: top;
  }

  .btn-primary td a {
    background-color: #62cb31;
    border: solid 1px #62cb31;
    border-radius: 3px;
    border-width: 4px 20px;
    display: inline-block;
    color: #ffffff;
    cursor: pointer;
    font-weight: bold;
    line-height: 2;
    text-decoration: none;
  }

  .last {
    margin-bottom: 0;
  }

  .first {
    margin-top: 0;
  }

  .padding {
    padding: 10px 0;
  }

  table.body-wrap {
    padding: 20px;
    width: 100%;
  }

  table.body-wrap .container {
    border: 1px solid #e4e5e7;
  }

  table.footer-wrap {
    clear: both !important;
    width: 100%;
  }

  .footer-wrap .container p {
    color: #666666;
    font-size: 12px;

  }

  table.footer-wrap a {
    color: #999999;
  }

  h1,
  h2,
  h3 {
    color: #111111;
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    font-weight: 200;
    line-height: 1.2em;
    margin: 40px 0 10px;
  }

  h1 {
    font-size: 36px;
  }
  h2 {
    font-size: 28px;
  }
  h3 {
    font-size: 22px;
  }

  p,
  ul,
  ol {
    font-size: 14px;
    font-weight: normal;
    margin-bottom: 10px;
  }

  ul li,
  ol li {
    margin-left: 5px;
    list-style-position: inside;
  }

  /* ---------------------------------------------------
  RESPONSIVENESS
  ------------------------------------------------------ */

  /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
  .container {
    clear: both !important;
    display: block !important;
    Margin: 0 auto !important;
    max-width: 1080px !important;
  }

  /* Set the padding on the td rather than the div for Outlook compatibility */
  .body-wrap .container {
    padding: 40px;
  }

  /* This should also be a block element, so that it will fill 100% of the .container */
  .content {
    display: block;
    margin: 0 auto;
    max-width: 1080px;
  }

  /* Let's make sure tables in the content area are 100% wide */
  .content table {
    width: 100%;
  }

  </style>
</head>

<body bgcolor="#f7f9fa">

  <table class="body-wrap" bgcolor="#f7f9fa">
    <tr>
      <td></td>
      <td class="container" bgcolor="#FFFFFF">

        <div class="content">
          <table>
            <tr>
              <td>
                {% block content %}
                <strong>Welcome in email template</strong>
                <p>Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
                <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised.</p>
                <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
                  <tr>
                    <td>
                      <a href="#">Simple button</a>
                    </td>
                  </tr>
                </table>
                <p>All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary</p>
                <p><a href="#">Follow @email_template on Twitter</a></p>
                {% endblock %}
              </td>
            </tr>
          </table>
        </div>

      </td>
      <td></td>
    </tr>
  </table>

  <table class="footer-wrap">
    <tr>
      <td></td>
      <td class="container">

        <div class="content">
          <table>
            <tr>
              <td align="center">
                {% block footer %}
                <p>Jennifer Convertibles</p>
                {% endblock %}
              </td>
            </tr>
          </table>
        </div>

      </td>
      <td></td>
    </tr>
  </table>

</body>
</html>