core/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

from dashboard.views import Dashboard


urlpatterns = [
    url(r'^$', Dashboard.as_view(), name="dashboard"),
    url(r'^index/$', Dashboard.as_view(), name="index"),
    url(r'^accounts/', include('authentication.urls', namespace='user')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^series/', include('series.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^webhooks/', include('webhooks.urls')),
    url(r'^discount/', include('discount.urls')),
]

vendors/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.VendorList.as_view(), name='vendor-list'),
    url(r'^create/$', views.VendorCreate.as_view(), name='vendor-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.VendorUpdate.as_view(), name='vendor-update'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.VendorDelete.as_view(), name='vendor-delete'),
]

vendors/models.py
from __future__ import unicode_literals

from django.db import models
from localflavor.us.models import PhoneNumberField

# Create your models here.
class Vendor(models.Model):
    name = models.CharField(max_length=128, unique=True)
    contact_person = models.CharField(max_length=128, blank=True)
    email = models.EmailField(blank=True, null=True)
    phone = PhoneNumberField(blank=True, null=True)

    def __unicode__(self):
        return self.name

vendors/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Vendor


class VendorMixin(LoginRequiredMixin):
    model = Vendor
    fields = ['code', 'name', 'contact_person', 'email', 'phone']
    success_url = reverse_lazy('vendor-list')


class VendorList(VendorMixin, ListView):
    pass


class VendorCreate(VendorMixin, CreateView):
    pass


class VendorUpdate(VendorMixin, UpdateView):
    pass


class VendorDelete(VendorMixin, DeleteView):
    pass

vendors/templates/vendors/vendor_confirm_delete.html
{% extends 'vendors/vendor_list.html' %}
{% load bootstrap3 %}

{% block breadcrumbs %}
  {{ block.super }}
	<li><a href="{% url 'vendor-update' object.pk %}">{{ object }}</a></li>
{% endblock %}

{% block content %}
<div class="hpanel">
  <div class="panel-body">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete this vendor? This action is not reversible.</p>
      <input type="submit"  class="btn btn-success" value="Confirm" />
    </form>
  </div>
</div>

{% endblock %}

vendors/templates/vendors/vendor_form.html
{% extends 'vendors/vendor_list.html' %}
{% load bootstrap3 %}

{% block title %}{{ object.name|default:"Create Vendor" }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
{% if object %}
	<li><a href="{% url 'vendor-update' object.pk %}">{{ object }}</a></li>
{% else %}
	<li><a href="{% url 'vendor-create' %}">Create</a></li>
{% endif %}
{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<form method="post">
			{% csrf_token %}
			{% bootstrap_form form %}
			{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
		</form>
	</div>
</div>

{% endblock %}

vendors/templates/vendors/vendor_list.html
{% extends 'base.html' %}

{% block title %}Vendors{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'vendor-list' %}">Vendors</a></li>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-3">
      <div class="hpanel hred contact-panel">
          <div class="panel-body">
              <h3 class="text-center"><a href="{% url 'vendor-create' %}"> <i class="fa fa-plus-circle"></i><br>Add Vendor </a></h3>
          </div>
      </div>
  </div>
  {% for object in object_list %}
  <div class="col-lg-3">
    <div class="hpanel hgreen contact-panel">
      <div class="panel-body">
        <h3><a href="">{{object.name}}</a></h3>
        <div class="text-muted font-bold m-b-xs">{{ object.contact_person }}</div>
        <p>
          Email: {{object.email}}<br>
          Phone: {{object.phone}} <br>
          <a class="btn btn-primary btn-sm" href="{% url 'vendor-update' object.pk %}">Edit</a>
          <a class="btn btn-danger btn-sm" href="{% url 'vendor-delete' object.pk %}">Delete</a>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}