core/urls.py
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

from dashboard.views import Dashboard


urlpatterns = [
    url(r'^$', Dashboard.as_view(), name="dashboard"),
    url(r'^index/$', Dashboard.as_view(), name="index"),
    url(r'^accounts/', include('authentication.urls', namespace='user')),
    url(r'^vendors/', include('vendors.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^series/', include('series.urls')),
    url(r'^schedule/', include('schedule.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^webhooks/', include('webhooks.urls')),
    url(r'^discount/', include('discount.urls')),
]

schedule/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.ScheduleListView.as_view(), name='schedule-list'),
    url(r'^create/$', views.ScheduleCreateView.as_view(), name='schedule-create'),
    url(r'^(?P<pk>[0-9]+)/', include([
        url(r'^$', views.ChangeListView.as_view(), name='schedule-detail'),
        url(r'^execute/$', views.ScheduleExecute.as_view(), name='schedule-execute'),
        # url(r'^(?P<pk>[0-9]+)/update$', views.ProductUpdate.as_view(), name='product-update'),
        url(r'^delete/$', views.ScheduleDeleteView.as_view(), name='schedule-delete'),
    ])),
    url(r'^changes/(?P<pk>[0-9]+)/', include([
        url(r'^delete/$', views.ChangeDeleteView.as_view(), name='change-delete'),
    ])),
]

schedule/models.py
from __future__ import unicode_literals
from decimal import Decimal

from django.db import models
from django.forms.models import model_to_dict
from django.contrib.postgres.fields import JSONField

from products.models import Product


class Schedule(models.Model):
    SCHEDULE_STATUS = (
        ('p', 'pending'),
        ('i', 'in progress'),
        ('e', 'error'),
        ('c', 'completed'),
    )
    SCHEDULE_TYPE=(
        ('manual', 'manual'),
        ('storewide', 'storewide discount'),
        ('collection', 'collection discount'),
        ('restore', 'restore'),
    )
    title = models.CharField(max_length=250)
    date = models.DateField()
    status = models.CharField(max_length=2, choices=SCHEDULE_STATUS, default='p')
    schedule_type = models.CharField(max_length=25, choices=SCHEDULE_TYPE,
                                     default='manual')
    discount = models.IntegerField(blank=True, null=True)
    clearance_discount = models.IntegerField(blank=True, null=True)
    exclude_promotion = models.BooleanField(default=False)
    theme = models.BigIntegerField(blank=True, null=True)
    coupons = models.CharField(max_length=250, default="None")
    task_total = models.IntegerField(default=0)
    task_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['-date']

    def __unicode__(self):
        return self.title

    def run_schedule(self):
        from .tasks import (discount_product, restore_product, update_theme,
                            disable_discounts, execute_change)
        for change in self.changes.all():
            execute_change.delay(change.id)
        # self.status = 'i'
        # self.task_total = 1 if self.theme else 0
        # if self.schedule_type == 'manual':
        #     self.task_total += self.changes.count()
        #     self.save()
        #     for product in Product.objects.filter(variants__changes__schedule=self):
        #         execute_change.delay(product.id, self.id)
        #     # for change in self.changes.all():
        #     #     change.run()
        # elif self.schedule_type == 'storewide':
        #     self.task_total += Product.main_products.count()
        #     self.save()
        #     for product in Product.main_products.all():
        #         discount_product.delay(
        #             model_to_dict(product), model_to_dict(self))
        # elif self.schedule_type == 'restore':
        #     queryset = Product.main_products.all()
        #     self.task_total += queryset.count()
        #     self.save()
        #     for product in queryset:
        #         restore_product.delay(model_to_dict(product), self.id)
        if self.theme:
            update_theme.delay(self.theme, self.id)
        # if self.coupons == '':
        #     disable_discounts.delay()


    @classmethod
    def update_status(cls, schedule_id, result):
        schedule = cls.objects.get(id=schedule_id)
        if result:
            schedule.task_count += 1
            if schedule.task_count == schedule.task_total and schedule.status == 'i':
                schedule.status = 'c'
        else:
            schedule.status = 'e'
        schedule.save()


class Change(models.Model):
    schedule = models.ForeignKey(Schedule, related_name="changes")
    product = models.ForeignKey('products.Product', related_name="changes")
    json = JSONField()
    completed = models.BooleanField(default=False)

    def run(self):
        from .tasks import execute_change
        execute_change.delay(self.id)

schedule/forms.py
from decimal import Decimal, ROUND_UP
from django import forms

from .models import *
from products.models import Variant


class ScheduleForm(forms.ModelForm):

    theme = forms.ChoiceField(required=False, choices=[])

    class Meta:
        model = Schedule
        fields = ['title', 'date', 'schedule_type', 'discount',
                  'clearance_discount', 'theme', 'coupons', 'exclude_promotion']

    def __init__(self, *args, **kwargs):
        super(ScheduleForm, self).__init__(*args, **kwargs)
        from products.utils import shopify
        themes = shopify.Theme.find()
        choices = [
            (None, 'None'),
        ]
        for theme in themes:
            choices.append((theme.id, theme.name))
        self.fields['theme'].choices = choices

    def clean_theme(self):
        data = self.cleaned_data['theme']
        if not data:
            return None
        return data

    def clean(self):
        data = super(ScheduleForm, self).clean()
        if data['schedule_type'] in ['storewide', 'collection']:
            if not data.get('discount', 0):
                self.add_error('discount', "Please add a discount rate.")


    def save(self, commit=True):
        instance = super(ScheduleForm, self).save(commit=False)
        if commit:
            instance.save()
            from schedule.tasks import generate_schedule_changes
            generate_schedule_changes.delay(instance.id)
        return instance

schedule/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DeleteView, DetailView)
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy, reverse

from .models import *
from .forms import *


class ScheduleMixin(LoginRequiredMixin):
    model = Schedule
    success_url = reverse_lazy('schedule-list')


class ScheduleListView(ScheduleMixin, ListView):
    pass


class ScheduleCreateView(ScheduleMixin, CreateView):
    form_class = ScheduleForm


class ScheduleDeleteView(ScheduleMixin, DeleteView):
    pass


class ScheduleExecute(ScheduleMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        schedule = get_object_or_404(Schedule, pk=kwargs['pk'])
        schedule.run_schedule()
        return reverse('schedule-list')


class ChangeDeleteView(LoginRequiredMixin, DeleteView):
    model = Change

    def get_success_url(self):
        return self.object.product.get_absolute_url()


class ChangeListView(LoginRequiredMixin, ListView):
    model = Change
    paginate_by = 20

    def dispatch(self, request, *args, **kwargs):
        self.object = get_object_or_404(Schedule, pk=self.kwargs.get('pk'))
        return super(ChangeListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(ChangeListView, self).get_queryset().filter(schedule=self.object)

    def get_context_data(self, **kwargs):
        context = super(ChangeListView, self).get_context_data(**kwargs)
        context['object'] = self.object
        return context

schedule/templates/schedule/change_confirm_delete.html
{% extends 'products/product_list.html' %}
{% load bootstrap3 %}

{% block title %}Delete Change?{% endblock %}

{% block actions %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'product-detail' object.product.pk %}">{{ object.product }}</a></li>
<li><a href="{% url 'change-delete' object.pk %}">Delete Change</a></li>
{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<form method="post">
			{% csrf_token %}
      <p>Are you sure you want to delete this change?</p>
			<button class="btn btn-danger">Delete</button>
			<a class="btn btn-default" href="{% url 'product-detail' object.product.pk %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

schedule/templates/schedule/change_list.html
{% extends 'schedule/schedule_list.html' %}
{% load bootstrap_pagination %}

{% block title %}{{ object }}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
<li><a href="{% url 'schedule-detail' object.pk %}">{{ object }}</a></li>
{% endblock %}

{% block actions %}
<a class="btn btn-primary" href="{% url 'schedule-delete' object.pk %}">Delete</a>
{% endblock %}

{% block content %}
<div class="hpanel">
  <div class="panel-body">
    <table class="table table-striped" >
      <thead>
        <tr>
          <th>Product</th>
          <th>Variant</th>
          <th>Sale Price</th>
          <th>Price</th>
          <th>Compare At Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for change in object_list %}
        {% for v in change.json %}
        <tr>
          <td>{% if forloop.first %}{{ change.product }}{% endif %}</td>
          <td>{{ v.title }}</td>
          <td>{{ v.sale_price }}</td>
          <td>{{ v.price }}</td>
          <td>{{ v.compare_at_price }}</td>
          <td>
            {% if forloop.first %}
              <a class="btn btn-xs btn-danger" href="{% url 'change-delete' change.pk %}">Delete</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
        {% endfor %}
      </tbody>
    </table>
    {% bootstrap_paginate page_obj range=10 %}
  </div>
</div>

{% endblock %}

schedule/templates/schedule/schedule_confirm_delete.html
{% extends 'schedule/schedule_list.html' %}
{% load bootstrap3 %}

{% block title %}Delete {{ object }}?{% endblock %}

{% block actions %}{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<form method="post">
			{% csrf_token %}
      <p>Are you sure you want to delete this schedule?</p>
			<button class="btn btn-danger">Delete</button>
			<a class="btn btn-default" href="{% url 'schedule-list' %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

schedule/templates/schedule/schedule_form.html
{% extends 'schedule/schedule_list.html' %}
{% load bootstrap3 %}

{% block title %}{{ object|default:"Create Schedule" }}{% endblock %}

{% block actions %}{% endblock %}

{% block breadcrumbs %}
{{ block.super }}
{% if object %}
	<li><a href="{% url 'schedule-update' object.pk %}">{{ object }}</a></li>
{% else %}
	<li><a href="{% url 'schedule-create' %}">Create</a></li>
{% endif %}
{% endblock %}

{% block content %}
<div class="hpanel">
	<div class="panel-body">
		<form method="post">
			{% csrf_token %}
      {% bootstrap_field form.title %}
      <div class="row">
        <div class="col-md-2">
          {% bootstrap_field form.date %}
        </div>
        <div class="col-md-2">
          {% bootstrap_field form.schedule_type %}
        </div>
        <div class="col-md-2">
          {% bootstrap_field form.discount %}
        </div>
				<div class="col-md-2">
          {% bootstrap_field form.clearance_discount %}
        </div>
				<div class="col-md-2">
          {% bootstrap_field form.exclude_promotion %}
        </div>
				<div class="col-md-2">
          {% bootstrap_field form.theme %}
        </div>
      </div>
			{% bootstrap_field form.coupons %}
			<button class="btn btn-success">Save Changes</button>
    </form>
  </div>
</div>
{% endblock %}

schedule/templates/schedule/schedule_list.html
{% extends 'base.html' %}

{% block title %}Schedules{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'schedule-list' %}">Schedule</a></li>
{% endblock %}

{% block actions %}
<a class="btn btn-primary" href="{% url 'schedule-create' %}">Add Schedule</a>
{% endblock %}

{% block content %}
<div class="hpanel">
  <div class="panel-body">
    <input type="text" class="form-control input-sm m-b-md" id="filter" placeholder="Search in table">
    <table class="table footable table-striped" data-filter="#filter">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Type</th>
          <th>Changes</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for object in object_list %}
      <tr>
        <td><a href="{% url 'schedule-detail' object.pk %}">{{ object.title }}</a></td>
        <td>{{ object.date }}</td>
        <td>{{ object.get_schedule_type_display }}</td>
        <td>{{ object.changes.count }}</td>
        <td>{{ object.get_status_display }}</td>
        <td>
          <a class="btn btn-xs btn-primary" href="{% url 'schedule-execute' object.pk %}">Execute</a>
          <a class="btn btn-xs btn-danger" href="{% url 'schedule-delete' object.pk %}">Delete</a>
        </td>
      </tr>
      {% empty %}
      <tr><td colspan="5" class="text-center">There are no schedules.</td></tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}